// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIVersionMeta) DeepCopyInto(out *APIVersionMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIVersionMeta.
func (in *APIVersionMeta) DeepCopy() *APIVersionMeta {
	if in == nil {
		return nil
	}
	out := new(APIVersionMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIVersionStatus) DeepCopyInto(out *APIVersionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIVersionStatus.
func (in *APIVersionStatus) DeepCopy() *APIVersionStatus {
	if in == nil {
		return nil
	}
	out := new(APIVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinalStatusResult) DeepCopyInto(out *FinalStatusResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinalStatusResult.
func (in *FinalStatusResult) DeepCopy() *FinalStatusResult {
	if in == nil {
		return nil
	}
	out := new(FinalStatusResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsedApiVersions) DeepCopyInto(out *UsedApiVersions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsedApiVersions.
func (in *UsedApiVersions) DeepCopy() *UsedApiVersions {
	if in == nil {
		return nil
	}
	out := new(UsedApiVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UsedApiVersions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsedApiVersionsList) DeepCopyInto(out *UsedApiVersionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UsedApiVersions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsedApiVersionsList.
func (in *UsedApiVersionsList) DeepCopy() *UsedApiVersionsList {
	if in == nil {
		return nil
	}
	out := new(UsedApiVersionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UsedApiVersionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsedApiVersionsSpec) DeepCopyInto(out *UsedApiVersionsSpec) {
	*out = *in
	if in.UsedApiVersions != nil {
		in, out := &in.UsedApiVersions, &out.UsedApiVersions
		*out = make([]APIVersionMeta, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsedApiVersionsSpec.
func (in *UsedApiVersionsSpec) DeepCopy() *UsedApiVersionsSpec {
	if in == nil {
		return nil
	}
	out := new(UsedApiVersionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsedApiVersionsStatus) DeepCopyInto(out *UsedApiVersionsStatus) {
	*out = *in
	if in.ApiVersionsStatus != nil {
		in, out := &in.ApiVersionsStatus, &out.ApiVersionsStatus
		*out = make([]APIVersionStatus, len(*in))
		copy(*out, *in)
	}
	out.FinalStatus = in.FinalStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsedApiVersionsStatus.
func (in *UsedApiVersionsStatus) DeepCopy() *UsedApiVersionsStatus {
	if in == nil {
		return nil
	}
	out := new(UsedApiVersionsStatus)
	in.DeepCopyInto(out)
	return out
}
